### ISSUE TITLE
Problems compiling  `analyze_networks`

### ISSUE THREAD

**Issue by dimitri-mar** [networkgeometry/directed-geometric-networks#2]
I tried to compile, following the instructions,  `analyze_networks`:
```
cd directed-geometric-networks/analyze_networks; cmake .; make; cd ../..
```
However, I get the error:

```
[...]directed-geometric-networks/analyze_networks/src/extract_network_properties.cpp:120:19: note: ‘std::setw’ is defined in header ‘<iomanip>’; this is probably fixable by adding ‘#include <iomanip>’
make[2]: *** [src/CMakeFiles/extract_network_properties.dir/build.make:76: src/CMakeFiles/extract_network_properties.dir/extract_network_properties.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:148: src/CMakeFiles/extract_network_properties.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```
I managed to solve it by including `#include <iomanip>` in all the `cpp` files in `analyze_networks/src`. 

I  do not know if this issue could be associated with my local configuration. If not, it is an easy fix, and if needed, I can open a PR.

**Comment by antoineallard** [comment]
Thank you for bringing this up. Please open a PR, so that we can avoid errors in the future (perhaps it comes from your local configuration, but adding iomanip anyway should not cause problem to other users).
